name: Documentation

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  docs:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install .
          pip install sphinx sphinx-rtd-theme
      - name: Building documentation
        working-directory: docs
        run: |
          #sphinx-apidoc -e -T -o source ../qmkpy
          make html
      - name: Saving documentation HTML
        uses: actions/upload-artifact@v3
        with:
          name: public
          path: docs/build/html

